"use client";
import ReduxProvider from "@/redux/ReduxProvider";
import Navbar from "./component/Navbar/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import QueryProvider from "./QueryProvider";
import Footer from "./component/company/footer/Footer";
import ApiUser from "./api/ApiUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <QueryProvider>
          <ReduxProvider>{children}</ReduxProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
